name: Security Audit

on:
  push:
    branches: ["main", "3.0", "3.3.6"]
  pull_request:
    branches: ["main", "3.0", "3.3.6"]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  cargo-deny:
    permissions:
      checks: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: EmbarkStudios/cargo-deny-action@v2
